config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :addresses
  resources :line_items
  
  resources :categories do 
    resources :items 
  end
  
  resources :carts
  resources :items 
  resources :orders
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'store#index' #, as: 'store'
  
  post '/orders' => 'orders#create', as: 'create_order'
  
  #Admin Routes
  resources :admin, only: [:index]
  get '/items_index' => 'admin#items', as: 'admin_items'
  get '/orders_index' => 'admin#orders', as: 'admin_orders'
  get '/show_order/:id' => 'admin#show_order'
  get '/admin_order/:id' => 'orders#admin_order'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Cart, Category, Item, Order]
    if user.present?
      can :manage, LineItem
      can :create, Order
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :items, through: :line_items
  belongs_to :user 
  
  def total
    self.items.map do |item| 
      item.price * self.line_items.find_by(item_id: item.id).quantity
      end.sum
  end
  
  def add_item(new_item_id)
    if line_item = self.line_items.find_by(item_id: new_item_id)
      line_item.quantity += 1
      line_item.save
      line_item
    else
      self.line_items.build(item_id: new_item_id.to_i)
    end
  end
  
  def remove_line_item(line_item_id)
    line_item = self.line_items.find_by(id: line_item_id)
    line_item.delete
  end
  
  def update_inventory
    self.items.each do |item|
      line_item = self.line_items.find_by(item_id: item.id)
      item.inventory -= line_item.quantity
      item.save
    end
  end
  
  def reset_cart
    self.destroy
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :line_items
  has_many :carts, through: :line_items 
  has_many :comments
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :price, presence: true
  validates :price, numericality: {message: "A number is required"}
  validates :inventory, presence: true
  validates :inventory, numericality: {message: "A number is required"}
  
  def self.available_items
    self.all.select do |item|
      item.inventory != 0
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items
  belongs_to :address
  accepts_nested_attributes_for :address
  
  def line_item_ids=(ids)
     ids.each do |id|
       line_item = LineItem.find(id)
       self.line_items << line_item
     end
  end
  
  def self.search_by_id(id)
    order_ary = []
    order = self.find_by(id: id)
    order_ary.push(order)
  end
  
  def self.search_by_email(email)
    if @user = User.find_by(email: email)
      @user.orders.select do |order|
        order
      end
    else
      false
    end
  end
  
  def self.search_by_status(status)
    self.all.select do |order|
      order.status == status
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :orders
  has_many :addresses, through: :orders
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         devise :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end      
    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/admin/index.html.erb
<% if current_user.admin %>
  <h3><%= link_to "All Orders", admin_orders_path%></h3>
  <h3><%= link_to "Add Item", new_item_path%></h3>
  <h3><%= link_to "Add Category", new_category_path%></h3>
  <h3><%= link_to "All Items", admin_items_path %><button type="button" id="js-all-items" class="btn btn-link">&or;</button></h3>
  <div class="js-items">
  </div>
<% end %>


<script type="text/javascript">
  $(function() {
    $('button#js-all-items').click(function (event) {
      $.getJSON('/items_index', function (itemsData) {
        var itemsList = "";
        itemsData.forEach(function(itemData){
          debugger;
          var item = new Item(itemData)
          itemsList+= item.buildHtml();
        });
        $('.js-items').html(itemsList)
      })
    });
  });
</script>

app/views/admin/items.html.erb
<h1>All Items</h1>

<% @items.each do |item| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>
        <%= link_to item.name, item_path(item) %> | <%= number_to_currency(item.price)%> | Invertory: <%= item.inventory %> | Category: <%= item.category.name %> | <%= link_to "Edit", edit_item_path(item), method: :get %>
      </h4>
    </div>
  </div>
<% end %>

app/views/admin/orders.html.erb
<!--Incorporate Search Box-->
<h1><%= link_to "All Orders", admin_orders_path %></h1>

<div>
  <h4>Filter orders:</h4>
  <%= form_tag("/orders_index", method: "get") do %>
    <%= search_field_tag "email", nil, placeholder: "Search by e-mail" %>
    <%= submit_tag "Filter" %>
    <%= search_field_tag "order_id", nil, placeholder: "Search by order #" %>
    <%= submit_tag "Filter" %>
    Search by status: <%= select_tag "status", options_for_select(["submitted", "shipped", "completed", "pending"]), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>

<% @orders.reverse.each do |order| %>
    <div class="panel-body">
      <a href="/admin_order/<%= order.id %>" class="list-group-item"><h4><%= order.user.email %> | Order #: <%= order.id %> | <%= order.created_at.strftime("Order Placed: %b %d, %Y") %> | Status: <%= order.status %> | <strong><%= number_to_currency(order.total) %></strong></h4></a>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<div>
  <%= content_tag(:div, flash[:error], id: "flash_error", class: "alert alert-danger" ) if flash[:error] %>
  <%= content_tag(:div, flash[:notice], id: "flash_notice", class: "alert alert-success", role: "alert") if flash[:notice] %>
  <%= content_tag(:div, flash[:alert], id: "flash_alert") if flash[:alert] %>
</div>

<!--<div class="alert alert-danger" role="alert"><%#= flash[:message] %></div>-->
<!--<div class="alert alert-success" role="alert"><%#=flash[:message]%></div>-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/">
    <img src="https://i.imgur.com/vmdGjqG.png" width="40" height="30 class="d-inline-block align-top" alt="">
    My Shopp
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="/">Home</a></li>
      <li role="presentation"><%= link_to "Categories", categories_path%></li>
      <% if user_signed_in? %>
        <li role="presentation"><%= link_to "Cart", cart_path(current_user.cart) if current_user.cart && current_user.cart.line_items != []%></li>
        <p class="navbar-text navbar-right text-muted">Signed in as <%= current_user.email %></p>
        <% if current_user.admin %>
          <li role="presentation"><%= link_to "Admin", admin_index_path %></li>
        <% else %>
           <li role="presentation"><%= link_to "Orders", orders_path if current_user.orders != []%></li>
        <% end %>
        <li role="presentation"><%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <li role="presentation"><%= link_to "Sign In",  new_user_session_path %></li>
        <li role="presentation"><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>

      <% end %>
    </ul>
</nav>
</nav>

app/views/layouts/_header_2.html.erb
<nav class="page-header">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">My Shop</a>
    </div>
    <div class="collapse navbar-collapse">
      <%= link_to "Categories", categories_path, class:"btn btn-default navbar-btn"%>
      <% if user_signed_in? %>
        <%= link_to "Cart", cart_path(current_user.cart), class:"btn btn-default navbar-btn" if current_user.cart%>
             <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
        <p class="navbar-text navbar-right">Signed in as <%= current_user.email %></p>
        <% if current_user.admin %>
          <%= link_to "Admin", admin_index_path, class:"btn btn-default navbar-btn" %>
        <% else %>
           <%= link_to "Orders", orders_path, class:"btn btn-default navbar-btn" if current_user.orders != []%>
        <% end %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"btn btn-default navbar-btn" %>
      <% else %>
        <%= link_to "Sign In",  new_user_session_path, class:"btn btn-default navbar-btn" %>
      <% end %>
    </div>
  </div>
</nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Shopp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
  
</html>