config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :addresses
  resources :line_items
  
  resources :categories do 
    resources :items 
  end
  
  resources :carts
  resources :items 
  resources :orders
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'store#index' #, as: 'store'
  
  post '/orders' => 'orders#create', as: 'create_order'
  
  #Admin Routes
  resources :admin, only: [:index]
  get '/items_index' => 'admin#items', as: 'admin_items'
  get '/orders_index' => 'admin#orders', as: 'admin_orders'
  get '/show_order/:id' => 'admin#show_order'
  get '/admin_order/:id' => 'orders#admin_order'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Cart, Category, Item, Order]
    if user.present?
      can :manage, LineItem
      can :create, Order
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :items, through: :line_items
  belongs_to :user 
  
  def total
    self.items.map do |item| 
      item.price * self.line_items.find_by(item_id: item.id).quantity
      end.sum
  end
  
  def add_item(new_item_id)
    if line_item = self.line_items.find_by(item_id: new_item_id)
      line_item.quantity += 1
      line_item.save
      line_item
    else
      self.line_items.build(item_id: new_item_id.to_i)
    end
  end
  
  def remove_line_item(line_item_id)
    line_item = self.line_items.find_by(id: line_item_id)
    line_item.delete
  end
  
  def update_inventory
    self.items.each do |item|
      line_item = self.line_items.find_by(item_id: item.id)
      item.inventory -= line_item.quantity
      item.save
    end
  end
  
  def reset_cart
    self.destroy
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :line_items
  has_many :carts, through: :line_items 
  has_many :comments
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :price, presence: true
  validates :price, numericality: {message: "A number is required"}
  validates :inventory, presence: true
  validates :inventory, numericality: {message: "A number is required"}
  
  def self.available_items
    self.all.select do |item|
      item.inventory != 0
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items
  belongs_to :address
  accepts_nested_attributes_for :address
  
  def line_item_ids=(ids)
     ids.each do |id|
       line_item = LineItem.find(id)
       self.line_items << line_item
     end
  end
  
  def self.search_by_id(id)
    order_ary = []
    order = self.find_by(id: id)
    order_ary.push(order)
  end
  
  def self.search_by_email(email)
    if @user = User.find_by(email: email)
      @user.orders.select do |order|
        order
      end
    else
      false
    end
  end
  
  def self.search_by_status(status)
    self.all.select do |order|
      order.status == status
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :orders
  has_many :addresses, through: :orders
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         devise :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end      
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def items
    @items = Item.all
    respond_to do |format|
      format.html { render :items }
      format.json { render json: @items }
    end
  end

  def orders
    handle_search_logic
  end

  private

  def handle_search_logic
    if @orders = Order.search_by_email(params[:email])
      @orders
    elsif !params[:order_id].blank? && params[:order_id] != "" && params[:order_id].to_i != 0
      @orders = Order.search_by_id(params[:order_id])
    elsif !params[:status].blank? && params[:status] != ""
      @orders = Order.search_by_status(params[:status])
    else
      @orders = Order.all
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource

  def index
    @orders = current_user.orders
  end

  def new
    @cart = current_user.cart
    @order = Order.new
    @order.build_address
  end

  def create
    @order = current_user.orders.build(order_params)
    if @order.save
      current_user.cart.update_inventory
      current_user.cart.reset_cart
      current_user.save
      flash[:notice] = "Order Submitted"
      redirect_to order_path(@order)
     else
      render :new
    end
  end

  def show
    if @order = current_user.orders.find_by(id: params[:id])
      #render show
    else
      redirect_to orders_path
    end
  end

  def admin_order
    if current_user.admin
      @order = Order.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    if current_user.admin
      @order = Order.find(params[:id])
      @order.status = params[:order][:status]
      @order.save
      redirect_to admin_orders_path
    else
      redirect_to root_path
    end
  end

  private

  def order_params
     params.require(:order).permit(:total, :status, line_item_ids: [], address_attributes: [:name, :street_address, :city, :state, :zipcode, :address_type, :user_id])
  end

  # def reset_current_cart
  #   current_user.cart.destroy
  #   current_user.cart = nil
  #   current_user.save
  # end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/orders/_errors.html.erb
<% @order.errors.full_messages.each do |error| %>
  <%= content_tag(:div, error, id: "flash_error", class: "alert alert-danger" ) %>
<% end %>

app/views/orders/admin_order.erb
<h1>Order #: <%= @order.id %></h1>
<%= link_to "All Orders", admin_orders_path%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @order.user.email %> | <%= @order.created_at.strftime("Order Placed: %b %d, %Y") %> | Status: <%= @order.status %> | <strong><%= number_to_currency(@order.total) %></strong></h3>
  </div>
  <% @order.line_items.each do |line_item| %>
    <div class="panel-body">
      <%= link_to line_item.item.name, item_path(line_item.item) %> | <%= number_to_currency(line_item.item.price) %> | Quantity: <%= line_item.quantity %>
    </div>
  <% end %>
  
  <% if @order.address %>
    <div class="panel-body">
      <strong>Shipp To:</strong></br>
      <%= @order.address.name %></br>
      <%= @order.address.street_address %></br>
      <%= @order.address.city %></br>
      <%= @order.address.state %>, <%= @order.address.zipcode %></br>
    </div>
  <% end %>
</div>


<%=form_for(@order) do |f| %>
  <%= f.label :status %>
  <%= f.select :status, ["submitted", "shipped", "completed", "pending"]%>
  
  <%= f.submit %>
<% end %>

app/views/orders/index.html.erb
<h1>Your Orders</h1>

<% @orders.reverse.each do |order| %>
  <div class="panel panel-default">
    <a href="/orders/<%= order.id %>" class="list-group-item">
      <h4>Order#: <%= order.id %> | <%= order.created_at.strftime("Order Placed: %b %d, %Y") %> | Status: <%= order.status %> | <strong><%= number_to_currency(order.total) %></strong></h4>
    </a>
  </div>
<% end %>

app/views/orders/new.html.erb
<%= render 'errors', locals: @order %>

<h1>Checkout</h1>
</br>

<%= form_for(@order) do |f|%>
  <div class="panel panel-default">
    <% current_user.cart.line_items.each do |line_item| %>
      <div class="panel-body">
        <%= line_item.item.name%> | <%= number_to_currency(line_item.item.price) %> | Quantity: <%= line_item.quantity %>
        <%= f.hidden_field :line_item_ids, :multiple => true, :value => line_item.id %>
      </div>
    <% end %>
  </div>

  <h4>Shipping Address: </h4>
  <%= f.fields_for :address do |addr| %>
    <%= addr.label :name %>
    <%= addr.text_field :name %><br>

    <%= addr.label :street_address %>
    <%= addr.text_field :street_address%><br>

    <%= addr.label :city %>
    <%= addr.text_field :city %><br>

    <%= addr.label :state %>
    <%= addr.text_field :state %><br>

    <%= addr.label :zipcode %>
    <%= addr.text_field :zipcode %><br>

    <%= addr.label :address_type %>
    <%= addr.text_field :address_type %><br>
    <%= addr.hidden_field :user_id, value: current_user.id %>

  <% end %>

  <h3>Order total: <strong><%= number_to_currency(current_user.cart.total) %></strong></h3>
  <%= f.hidden_field :total, :value => current_user.cart.total%>
  <%= f.hidden_field :status, :value => "submitted" %>
  </br>

  <%= button_to "Submit Order", create_order_path, class:"btn btn-primary"%>

<% end %>

app/views/orders/show.html.erb
<h1>Order#: <%= @order.id %></h1>

</br>
<p><%= @order.created_at.strftime("Order Placed: %b %d, %Y") %> | Status: <%= @order.status %></p>
</br>

<% @order.line_items.each do |line_item| %>
  <p><%= link_to line_item.item.name, item_path(line_item.item) %> | <%= number_to_currency(line_item.item.price) %> | Quantity: <%= line_item.quantity %></p>
  <% end %>


<% if @order.address %>
  <strong>Shipp To:</strong></br>
  <%= @order.address.name %></br>
  <%= @order.address.street_address %></br>
  <%= @order.address.city %></br>
  <%= @order.address.state %>, <%= @order.address.zipcode %></br>
<% end %>

<h3>Order total: <strong><%= number_to_currency(@order.total) %></strong> </h3>
 