config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :addresses
  resources :line_items
  
  resources :categories do 
    resources :items 
  end
  
  resources :carts
  resources :items 
  resources :orders
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'store#index' #, as: 'store'
  
  post '/orders' => 'orders#create', as: 'create_order'
  
  #Admin Routes
  resources :admin, only: [:index]
  get '/items_index' => 'admin#items', as: 'admin_items'
  get '/orders_index' => 'admin#orders', as: 'admin_orders'
  get '/show_order/:id' => 'admin#show_order'
  get '/admin_order/:id' => 'orders#admin_order'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Cart, Category, Item, Order]
    if user.present?
      can :manage, LineItem
      can :create, Order
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :items, through: :line_items
  belongs_to :user 
  
  def total
    self.items.map do |item| 
      item.price * self.line_items.find_by(item_id: item.id).quantity
      end.sum
  end
  
  def add_item(new_item_id)
    if line_item = self.line_items.find_by(item_id: new_item_id)
      line_item.quantity += 1
      line_item.save
      line_item
    else
      self.line_items.build(item_id: new_item_id.to_i)
    end
  end
  
  def remove_line_item(line_item_id)
    line_item = self.line_items.find_by(id: line_item_id)
    line_item.delete
  end
  
  def update_inventory
    self.items.each do |item|
      line_item = self.line_items.find_by(item_id: item.id)
      item.inventory -= line_item.quantity
      item.save
    end
  end
  
  def reset_cart
    self.destroy
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :line_items
  has_many :carts, through: :line_items 
  has_many :comments
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :price, presence: true
  validates :price, numericality: {message: "A number is required"}
  validates :inventory, presence: true
  validates :inventory, numericality: {message: "A number is required"}
  
  def self.available_items
    self.all.select do |item|
      item.inventory != 0
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items
  belongs_to :address
  accepts_nested_attributes_for :address
  
  def line_item_ids=(ids)
     ids.each do |id|
       line_item = LineItem.find(id)
       self.line_items << line_item
     end
  end
  
  def self.search_by_id(id)
    order_ary = []
    order = self.find_by(id: id)
    order_ary.push(order)
  end
  
  def self.search_by_email(email)
    if @user = User.find_by(email: email)
      @user.orders.select do |order|
        order
      end
    else
      false
    end
  end
  
  def self.search_by_status(status)
    self.all.select do |order|
      order.status == status
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :orders
  has_many :addresses, through: :orders
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         devise :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end      
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def items
    @items = Item.all
    respond_to do |format|
      format.html { render :items }
      format.json { render json: @items }
    end
  end

  def orders
    handle_search_logic
  end

  private

  def handle_search_logic
    if @orders = Order.search_by_email(params[:email])
      @orders
    elsif !params[:order_id].blank? && params[:order_id] != "" && params[:order_id].to_i != 0
      @orders = Order.search_by_id(params[:order_id])
    elsif !params[:status].blank? && params[:status] != ""
      @orders = Order.search_by_status(params[:status])
    else
      @orders = Order.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def new
    if params[:category_id]
      @category = Category.find_by(id: params[:category_id])
      @item = Item.new
    else
      @category = Category.new
      @item = Item.new
    end
  end

  def show
    @comment = Comment.new
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @item }
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "Item created"
      redirect_to item_path(@item)
     else
      render :new
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    flash[:notice] = "item deleted."
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :inventory, :price, :description, :category_id, :img_src)
  end

  def set_item
    @item = Item.find_by(id: params[:id])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/items/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.label "Leave a comment:"%><br/>
  <%= f.text_field :text%>

  <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.hidden_field :item_id, :value => @item.id %>
  <br></br>

  <%= f.submit nil, id: "submit-comment"%>
<% end %>

app/views/items/_errors.html.erb
<% @item.errors.full_messages.each do |error| %>
  <%= content_tag(:div, error, id: "flash_error", class: "alert alert-danger" ) %>
<% end %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br>
  
  <%= f.label :price %></br>
  <%= f.text_field :price %></br>
  
  <%= f.label :inventory %></br>
  <%= f.text_field :inventory %></br>
  
  <%= f.label :category %></br>
  <% if @category && @category.name %>
    <p><%= @category.name %></p>
    <%= f.hidden_field :category_id, value: @category.id %></br>
  <% else %>
    <%= f.collection_select :category_id, Category.all, :id, :name %></br>
  <% end %>
  
  <%= f.label :description %></br>
  <%= f.text_field :description %></br>
  </br>
  
  <div class="btn-group">
    <p> <%= f.submit nil, class:"btn btn-primary" %></p>
  </div>
  
<% end %>

app/views/items/_image.html.erb
<% if @item.img_src %>
  <div class= "thumbnail">
     <img src="<%= @item.img_src%>"> </img>
  </div>
<% end %>

app/views/items/_item.html.erb
<% if !@item.description.nil? && @item.description != "" %>
     <%= @item.description %> 
<% end %>

<div class= "green"><h2><%= number_to_currency(@item.price) %></h2></div>

<% if @item.inventory == 0 %>
  <div class="fire-brick">
    <p>
      <strong>Item is out of stock.</strong>
    </p>
  </div>
<% elsif @item.inventory < 3  %>
    <div class="fire-brick">
    <p>
      <strong>There are only <%= @item.inventory %> items left in stock.</strong>
    </p>
  </div>
<% end %>

<% if can? :edit, @item %>
  <h3>Inventory: <%= @item.inventory%></h3>
  <p><%= button_to "Edit", edit_item_path, method: :get, class: "btn btn-warning"%></p>
<% end %>

<%= button_to 'Add to Cart', line_items_path(item_id: @item),  class:"btn btn-primary" if @item.inventory != 0 %>

app/views/items/edit.html.erb
<%= render 'errors', locals: @item %>

<h1>Edit Item </h1>

<%= render 'form', locals: @item %>

<div class="btn-group">
  <p><%= button_to "Delete", item_path(@item), method: :delete, class: "btn btn-danger"%></p>
</div>

app/views/items/new.html.erb
<%= render 'errors', locals: @item %>

<h1>Add Item <%="To #{@category.name}" if @category && @category.name %></h1>

<%= render 'form', locals: [@item, @category] %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<div class= "row">
  <div class="col-sm-6 col-md-4 ">
     <%= render 'image', locals: @item %>
    <div class="card">
      <%= render 'item', locals: @item %>
    </div>
  </div>
</div>

<br>

<% if @item.comments != [] %>
  <h4><a href="#" id="js-comments" data-id="<%= @item.id %>">Show Comments</a></h4>
<% end %>

<div id="js-view-comments">
</div>

<% if current_user %>
  <%= render 'comment_form', locals: @comment %>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('#js-comments').click(function(e){
      e.preventDefault();
      const id = $(this).data("id")
      $.getJSON(`/items/${id}`, function(itemData) {
        const comments = itemData['comments']
        let commentsList = "";

        comments.sort(function(a, b){
          let dateA = new Date(a.created_at)
          let dateB = new Date(b.created_at)

          if (dateA > dateB) {
            return -1
          } else {
            return 1
          }
        });

        comments.forEach(function (commentData) {
          const comment = new Comment(commentData);
          commentsList += comment.buildHtml();
        })

        $('#js-view-comments').html(commentsList);
      });
    });
  });
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form#new_comment').on("submit", function(event) {
      event.preventDefault();
      const values = $(this).serialize();
      const posting = $.post('/comments', values);

      posting.done(function(commentData) {
        const comment = new Comment(commentData)
        const commentFormat = comment.buildHtml();
        $('#js-view-comments').append(commentFormat);
        document.getElementById('submit-comment').disabled = false;
        $('#comment_text').val('');
      });
    });
  });
</script>