config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :addresses
  resources :line_items
  
  resources :categories do 
    resources :items 
  end
  
  resources :carts
  resources :items 
  resources :orders
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'store#index' #, as: 'store'
  
  post '/orders' => 'orders#create', as: 'create_order'
  
  #Admin Routes
  resources :admin, only: [:index]
  get '/items_index' => 'admin#items', as: 'admin_items'
  get '/orders_index' => 'admin#orders', as: 'admin_orders'
  get '/show_order/:id' => 'admin#show_order'
  get '/admin_order/:id' => 'orders#admin_order'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Cart, Category, Item, Order]
    if user.present?
      can :manage, LineItem
      can :create, Order
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :orders
  belongs_to :user

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :items, through: :line_items
  belongs_to :user 
  
  def total
    self.items.map do |item| 
      item.price * self.line_items.find_by(item_id: item.id).quantity
      end.sum
  end
  
  def add_item(new_item_id)
    if line_item = self.line_items.find_by(item_id: new_item_id)
      line_item.quantity += 1
      line_item.save
      line_item
    else
      self.line_items.build(item_id: new_item_id.to_i)
    end
  end
  
  def remove_line_item(line_item_id)
    line_item = self.line_items.find_by(id: line_item_id)
    line_item.delete
  end
  
  def update_inventory
    self.items.each do |item|
      line_item = self.line_items.find_by(item_id: item.id)
      item.inventory -= line_item.quantity
      item.save
    end
  end
  
  def reset_cart
    self.destroy
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :line_items
  has_many :carts, through: :line_items 
  has_many :comments
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :price, presence: true
  validates :price, numericality: {message: "A number is required"}
  validates :inventory, presence: true
  validates :inventory, numericality: {message: "A number is required"}
  
  def self.available_items
    self.all.select do |item|
      item.inventory != 0
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items
  belongs_to :address
  accepts_nested_attributes_for :address
  
  def line_item_ids=(ids)
     ids.each do |id|
       line_item = LineItem.find(id)
       self.line_items << line_item
     end
  end
  
  def self.search_by_id(id)
    order_ary = []
    order = self.find_by(id: id)
    order_ary.push(order)
  end
  
  def self.search_by_email(email)
    if @user = User.find_by(email: email)
      @user.orders.select do |order|
        order
      end
    else
      false
    end
  end
  
  def self.search_by_status(status)
    self.all.select do |order|
      order.status == status
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  has_many :orders
  has_many :addresses, through: :orders
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         devise :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end      
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def items
    @items = Item.all
    respond_to do |format|
      format.html { render :items }
      format.json { render json: @items }
    end
  end

  def orders
    handle_search_logic
  end

  private

  def handle_search_logic
    if @orders = Order.search_by_email(params[:email])
      @orders
    elsif !params[:order_id].blank? && params[:order_id] != "" && params[:order_id].to_i != 0
      @orders = Order.search_by_id(params[:order_id])
    elsif !params[:status].blank? && params[:status] != ""
      @orders = Order.search_by_status(params[:status])
    else
      @orders = Order.all
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @categories = Category.all
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @category }
    end
  end

  def new
    @category = Category.new
  end

  def create
    if @category = Category.find_by(name: params[:category][:name])
      flash[:error] = "#{@category.name} Already created."
      redirect_to category_path(@category)
    else
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Category created"
        redirect_to category_path(@category)
       else
        render :new
      end
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      redirect_to edit_category(@category)
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category deleted."
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

#   def set_category
#     @category = Category.find_by(id: params[:id])
#   end
# end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/categories/_errors.html.erb
<% @category.errors.full_messages.each do |error| %>
  <%= content_tag(:div, error, id: "flash_error", class: "alert alert-danger" ) %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'errors', locals: @category %>

<h1>Edit Category</h1>
<br></br>

<%= form_for(@category) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br></br>
  
  <div class="btn-group">
    <p> <%= f.submit nil, class:"btn btn-primary" %></p>
  </div>
  
<% end %>

<div class="btn-group">
  <p><%= button_to "Delete", category_path(@category), method: :delete, class: "btn btn-danger"%></p>
</div>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <h2><%= link_to category.name, category_path(category)%><button type="button" class="btn btn-link" data-id="<%= category.id %>">&or;</button></h2>
  <ul id="category-item-<%= category.id %>">
  </ul>
<% end %>

<% if can? :create, @category %>
  <p><%= button_to "Add New Category", new_category_path, method: :get, class:"btn btn-success" %></p>
<% end %>

<script type="text/javascript">
  $(function(){
    $(".btn.btn-link").on("click", function(){
      const id = $(this).data("id");
      $.getJSON(`/categories/${id}`, function(categoryData){
        const items = categoryData["items"]
        let itemsList = "";

        items.forEach(function(item) {
          itemsList+= `<li><a href="/items/${item.id}">${item.name} | $${item.price.toLocaleString()}</a></li>`;
        });
        $(`#category-item-${id}`).html(itemsList)
      });
    });
  });
</script>

app/views/categories/new.html.erb
<%= render 'errors', locals: @category %>

<h1>Add Category</h1>
</br>

<%= form_for(@category) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br></br>
  <%= f.submit nil, class:"btn btn-primary" %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @category.items.each do |item| %>
  <h3><%= link_to "#{item.name} | #{number_to_currency(item.price)}", item_path(item) %></h3>
<% end %>

<% if can? :create, Item %>
  </br>
  <div class= "btn-group"><%= button_to "New Item", new_category_item_path(@category.id), method: :get, class:"btn btn-success"%></div>
  <div class= "btn-group"><%= button_to "Edit Category", edit_category_path(@category.id), method: :get, class: "btn btn-warning"%></div>
<% end %>